lib_info_link = [
    "https://flexiple.com/python/python-libraries",
    "https://www.geeksforgeeks.org/libraries-in-python/",
    "https://www.geeksforgeeks.org/python-libraries-to-know/",
    "https://www.wscubetech.com/resources/python/libraries",
    "https://dev.to/taipy/top-42-python-libraries-you-need-to-know-1omo",
    "https://simurghai.com/here-is-a-table-of-100-python-libraries-grouped-by-functionality/631/",
    "https://www.datacamp.com/blog/top-python-libraries-for-data-science",
    "https://numpy.org/doc/stable/user/absolute_beginners.html",
    "https://pip.pypa.io/en/stable/installation/",
    "https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html",
    "https://numpy.org/install/",
    "https://pandas.pydata.org/getting_started.html",
    "https://scikit-learn.org/stable/install.html",
    "https://www.tensorflow.org/install",
    "https://pytorch.org/get-started/locally/",
    "https://huggingface.co/docs/transformers/installation",
    "https://spacy.io/usage",
    "https://www.nltk.org/install.html",
    "https://flask.palletsprojects.com/en/latest/installation/",
    "https://docs.djangoproject.com/en/stable/topics/install/",
    "https://fastapi.tiangolo.com/#installation",
    "https://matplotlib.org/stable/users/installing.html",
    "https://seaborn.pydata.org/installing.html",
    "https://plotly.com/python/getting-started/",
    "https://docs.sqlalchemy.org/en/latest/intro.html#installation",
    "https://pymongo.readthedocs.io/en/stable/installation.html",
    "https://opencv.org/releases/",
    "https://pillow.readthedocs.io/en/stable/installation.html",
    "https://requests.readthedocs.io/en/latest/user/install/",
    "https://aiohttp.readthedocs.io/en/stable/#installation",
    "https://scrapy.org/download/",
    "https://beautiful-soup-4.readthedocs.io/en/latest/#installing-beautiful-soup",
    "https://pytest.org/en/latest/getting-started.html#install-pytest",
    "https://docs.pytest.org/en/latest/getting-started.html#install-pytest",
    "https://docs.celeryq.dev/en/stable/getting-started/installation.html",
    "https://bokeh.org/install/",
    "https://streamlit.io/install",
    "https://dash.plotly.com/installation",
    "https://pydantic-docs.helpmanual.io/install/",
    "https://pyyaml.org/wiki/PyYAML",
    "https://docs.scipy.org/doc/scipy/getting_started.html",
    "https://networkx.org/documentation/stable/install.html",
    "https://pytorch-lightning.readthedocs.io/en/stable/getting_started/installation.html",
    "https://xgboost.readthedocs.io/en/stable/install.html",
    "https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html",
    "https://pycaret.gitbook.io/docs/get-started/installation",
    "https://optuna.readthedocs.io/en/stable/installation.html",
    "https://shap.readthedocs.io/en/latest/#installation",
    "https://eli5.readthedocs.io/en/latest/overview.html#installation",
    "https://deap.readthedocs.io/en/master/#installation",
    "https://tqdm.github.io/docs/tqdm/",
    "https://fastapi.tiangolo.com/deployment/docker/",
    "https://flairnlp.github.io/docs/install",
    "https://pypi.org/project/gensim/",
    "https://pypi.org/project/sentence-transformers/",
    "https://pypi.org/project/langchain/",
    "https://pypi.org/project/faiss-cpu/",
    "https://pypi.org/project/transformers/",
    "https://pypi.org/project/datasets/",
    "https://pypi.org/project/torchvision/",
    "https://pypi.org/project/torchaudio/",
]

FASTAPI_URL_QUERY = "http://127.0.0.1:8000/generate-response/"
LOG_LEVEL = "DEBUG"
CHAT_DB_LOC = "v5/backend/history/chats.db"
LOG_FILE_LOC = "v5/backend/history/app.log"
VECTOR_INDEX_LOC = "v5/backend/faiss_index"
BM25_INDEX_LOC = "v5/backend/bm25_index.pkl"
