query_creation_task:
  description: >
    Based on the given request {query}. Focus on:
    1. Constructing optimized SQL query to retrieve the required data.
    2. Execute the SQL query and retrieve the dataset.
    3. If no data is found for given query, respond with `No data found for the requested query.`
    4. Save the retrieved dataset in a JSON file.
  expected_output: >
    A well-structured dataset containing the relevant database records based on the query 
    or a "No data found for the requested query." message if applicable.
    Dataset stored in a json file
    Gather the output names and use `GatherAndMoveOutputsTool` to store outputs in a single folder named as outputs.
    If all output files is already saved in outputs folder then no need to execute this tool
  agent: data_engineer


analysis_task:
  description: >
    Perform a thorough analysis of the dataset retrieved for the request: {query}. 
    Identify key patterns, trends, and insights using statistical techniques and visualizations. 
    Highlight meaningful findings, trends, anomalies, and actionable recommendations. 
    If no data is available, acknowledge the absence and provide brief context.
    Save summary to a markdown file.
    Code should have a result variable that will store all the summary stats.
  expected_output: >
    A detailed and insightful analysis that includes key findings, statistical summaries, 
    visualizations, and actionable recommendations, or a brief acknowledgment if no data is found.
    Summary reports saved to a markdown file.
    Gather the output names and use `GatherAndMoveOutputsTool` to store outputs in a single folder named as outputs
    If all output files is already saved in outputs folder then no need to execute this tool
  agent: data_analyst
